# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 'BAF Pipelines Development'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          docker build . -t escalation-bafcare-fe:$(tag)
          docker container stop escalation-bafcare-fe
          docker container rm escalation-bafcare-fe

- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    pool: 'BAF Pipelines Development'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          docker run --name escalation-bafcare-fe -p 3121:3121 -d escalation-bafcare-fe:$(tag)
          docker image rm -f escalation-bafcare-fe:$(tag)